name: setup test
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  make:
    runs-on: macos-14

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Add execution permissions to scripts
        run: |
          chmod +x .bin/init.sh
          chmod +x .bin/macos_custom_settings.sh
          chmod +x .bin/brew.sh

      - name: Setup dotfiles
        run: make
      
      - name: Confirm Python version
        run: |
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"
          pyenv install 3.12.0
          python --version

      - name: Confirm Node version
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$(brew --prefix nvm)/nvm.sh" ] && \. "$(brew --prefix nvm)/nvm.sh"
          nvm install 22
          node -v
